---
- name: Configurar cliente NFS
  hosts: localhost
  connection: local
  tasks:
    - ansible.builtin.import_tasks:
        file: nfs/tasks/instalar_nfs.yml

    - ansible.builtin.import_tasks:
        file: nfs/tasks/configurar_nfs.yml
