---
- name: Configuração adicional
  hosts: localhost
  connection: local
  tasks:
    - name: Reparar hfscrspstm — link simbólico do python2.5
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Editar o arquivo de configuração do servidor ssh /etc/sshd_config
      ansible.builtin.copy:
        src: files/sshd_config
        dest: /etc/sshd_config
        mode: 0644

    - name: Recarregar serviço ssh
      ansible.builtin.systemd:
        name: ssh
        state: reloaded
